#define HARDCODED_TIME_TO_DISCHARGE_MS 1 * 60 * 1000
#define HARDCODED_TIME_TO_RECHARGE_MS 30 * 1000
#define HARDCODED_THRESHOLD_DISTANCE_CM 30
#define WIFI_SSID "Prepodavatelskaya"
#define WIFI_PASSWORD "prepod13840"
#define FIREBASE_HOST " smart-chair-d821f.firebaseio.com"
#define FIREBASE_SECRET "l1hNYcq8fVGPfwcq7LMkgWFLODzPaMd9xVe31BVL"
